### ISSUE TITLE
Gray screen after update

### ISSUE THREAD

**Issue by nwilson1412** [KomodoPlatform/agama-mobile#64] opened 2019-05-26 02:54 UTC
Pixel 2 - Android  9 - Agama 0.1.7
Recent reviews on google Play store seem to indicate it isnt an isolated issue. 
Once app is opened, it shows the Agama logo, then the entire screen goes gray.
I've updated to the latest version, and cleared cache and issue is persisting. 
I havent cleared storage as a troubleshooting step, as I'd want to make sure I can find my backup seed phrases before I remove everything.

**Comment by tonymorony** [comment] 2019-05-26 03:27
@nwilson1412 thank you for report. Unfortunately not able to reproduce at the moment on any of my Android devices.

Do you use wifi or mobile network?

**Comment by nwilson1412** [comment] 2019-05-26 03:36
I've tested with both WiFi and mobile network, both are having the same issue

**Comment by shardwatch** [comment] 2019-05-26 09:25
Same with iOS for me.
It happened after an update but before current version.  Updated to latest.  Same.

Uninstall and reinstall v0.1.6(791) fixed blank screen issue.  Have option to restore wallet

**Comment by tonymorony** [comment] 2020-03-04 10:19
Closing this one: Agama mobile is deprecated software

**Closed as completed by tonymorony** 2020-03-04 10:19 UTC
Labels: Android, bug-report
